export const COLLEGE_LOGO_FALLBACK = '/assets/placeholder.png'; // Using existing placeholder as fallback

export const normalizeCollegeLogoKey = (value: string = "") =>
    value
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9]+/g, "_")
        .replace(/^_+|_+$/g, "");

export const resolveCollegeLogo = (
    collegeName: string
) => {
    const rawName = collegeName || "";
    const nameKey = normalizeCollegeLogoKey(rawName);

    const logoAliases: { [key: string]: string } = {
        caltech: "california_institute_of_technology_caltech",
        california_institute_of_technology: "california_institute_of_technology_caltech",
        california_institute_of_technology_caltech: "california_institute_of_technology_caltech",
        "uc_berkeley": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley": "university_of_california_berkeley",
        "uc_berkeley_university_of_california": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_uc_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb": "university_of_california_berkeley",
        "university_of_california_berkeley_cal": "university_of_california_berkeley",
        "university_of_california_berkeley_uc": "university_of_california_berkeley",
        "university_of_california_berkeley_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_u_c_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_university_of_california": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ca_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ca_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_ca_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_u_c_berkeley_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_ca_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ca_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_u_c_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_ca_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_california_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_cal": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ca_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ca_usa_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_ca_california": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_usa_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_ca_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ca_usa_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_ca_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_ca_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_california_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_berkeley_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_berkeley_ca_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_ca_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_usa_california": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_ca_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_ca_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_usa_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_california_usa_berkeley_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_california_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_ca": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_california_berkeley_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_california_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_california_berkeley_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_ca_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_ca_usa_california": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_ca_usa_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_california_usa_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        // Modified by Abhradip Paul Duplicate field here
        // "university_of_california_berkeley_uc_berkeley_ucb_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_california_usa_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_uc_berkeley_ucb_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "university_of_california_berkeley_ucb_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "ucb": "university_of_california_berkeley",
        "ucb_cal": "university_of_california_berkeley",
        "uc_berekeley": "university_of_california_berkeley",
        "uc_berkeley_cal": "university_of_california_berkeley",
        "uc_berkeley_ucb": "university_of_california_berkeley",
        "uc_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_berkeley": "university_of_california_berkeley",
        "uc_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_usa": "university_of_california_berkeley",
        "uc_berkeley_california_berkeley": "university_of_california_berkeley",
        "uc_berkeley_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_berkeley_usa": "university_of_california_berkeley",
        "uc_berkeley_ca_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_california_berkeley_usa": "university_of_california_berkeley",
        "uc_berkeley_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_ca_california": "university_of_california_berkeley",
        "uc_berkeley_california_ca": "university_of_california_berkeley",
        "uc_berkeley_uc": "university_of_california_berkeley",
        // Modified by Abhradip Paul Duplicate field here
        // "uc_berkeley_university_of_california": "university_of_california_berkeley",
        // "uc_berkeley_university_of_california_berkeley": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_ca": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_usa": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_california_usa_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_california_usa_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_university_of_california_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_ca": "university_of_california_berkeley",
        "uc_berkeley_ucb_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_ucb_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_berkeley_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_ca_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_california_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_california_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_ca": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_ca_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california": "university_of_california_berkeley",
        "uc_berkeley_ucb_usa_california_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa_berkeley_california_usa": "university_of_california_berkeley"
    };

    const resolvedKey = logoAliases[nameKey] || nameKey;

    // Assuming images are available at /logos/[key].png
    // We return the path. The component using this can handle onError for fallback.
    return {
        logoSrc: `/logos/${resolvedKey}.png`,
        fallbackLogo: COLLEGE_LOGO_FALLBACK
    };
};
