import { Property } from '@/components/dashboard/main/empty-listing';
import { atomWithStorage } from 'jotai/utils';

export const claimPropertyAtom = atomWithStorage<Property>('claim-property', {
  propertyAddressDetails: {
    formattedAddress: '',
    city: '',
    postalCode: '',
    country: '',
    placeId: '',
    province: '',
    state: '',
    streetName: '',
    streetNumber: '',
    longitude: '',
    latitude: '',
  },
  images: [],
  propertyDocument: [],
  propertyName: '',
  longitude: '',
  latitude: '',
  price: {
    amount: 0,
    currency: '',
  },
  propertyType: '',
  propertyDescription: '',
  videos: [],
  lotSizeValue: '',
  numBathroom: '',
  numBedroom: '',
  yearBuild: 0,
  lotSizeUnit: '',
  _id: '',
  listed: false,
  currentStatus: '',
  seller: undefined,
  sellerAgentAcceptance: false,
  buyerAgentAcceptance: false,
  brokers: [],
  features: [],
  propertyTaxes: [],
  status: [],
  createdAt: '',
  updatedAt: '',
  sellerAgent: undefined,
  buyerAgent: undefined,
});
