export interface MlsMedia {
  Order: number;
  MediaKey: string;
  MediaURL: string;
  MediaSize: number;
  ImageHeight: number;
  MediaModificationTimestamp: string;
  ImageWidth: number;
  Thumbnail: string;
  ImageSizeDescription: string;
  MediaObjectID: string;
}

export interface MlsPropertyListing {
  ListingKey: string;
  ModificationTimestamp: string;
  ListingId: string;
  PropertyType: string;
  PropertySubType: string;
  ListPrice: number;
  BathroomsTotalInteger: number;
  BedroomsTotal: number;
  StandardStatus: string;
  LotSizeArea: number | null;
  LivingArea: number;
  BuildingAreaTotal: number;
  ListAgentFullName: string;
  ListAgentMlsId: string;
  ListOfficeMlsId: string;
  ListOfficeName: string;
  OriginatingSystemName: string | null;
  City: string;
  PostalCode: string;
  Coordinates: [number, number];
  Latitude: number;
  Longitude: number;
  BathroomsHalf: number;
  YearBuilt: number;
  InternetAddressDisplayYN: boolean;
  Media: MlsMedia[];
  UnparsedAddress: string | null;
  PublicRemarks: string;
  Gas: string[];
  DOH1: string | null;
  DOH2: string | null;
  DOH3: string | null;
  Make: string | null;
  Roof: string[];
  View: string[];
  Model: string | null;
  Sewer: string[];
  Skirt: string[];
  SpaYN: boolean;
  Levels: string[];
  MapURL: string | null;
  TaxLot: string;
  ViewYN: boolean;
  Zoning: string;
  CapRate: number | null;
  Cooling: string[];
  Country: string;
  Fencing: string[];
  Heating: string[];
  HorseYN: boolean;
  ListAOR: string | null;
  SerialU: string | null;
  SerialX: string | null;
  Stories: number;
  TaxYear: number;
  Basement: string[];
  BodyType: string[];
  Electric: string[];
  Flooring: string[];
  GarageYN: boolean;
  License1: string | null;
  License2: string | null;
  License3: string | null;
  MaloneId: string | null;
  ParkName: string | null;
  RoomType: string | null;
  SerialXX: string | null;
  TaxBlock: string;
  TaxTract: string;
  Township: string | null;
  '@odata.id': string;
  CarportYN: boolean;
  CloseDate: string | null;
  CoolingYN: boolean;
  Elevation: number;
  Furnished: string | null;
  HeatingYN: boolean;
  LeaseTerm: string | null;
  MlsStatus: string;
  OwnerName: string | null;
  OwnerPays: string[];
  Ownership: string;
  RangeArea: string | null;
  Telephone: string[];
  Utilities: string[];
  WalkScore: number | null;
  AccessCode: string;
  Appliances: string[];
  CityRegion: string;
  ClosePrice: number | null;
  CurrentUse: string[];
  Directions: string;
  Disclaimer: string;
  EntryLevel: number | null;
  Exclusions: string;
  HighSchool: string;
  Inclusions: string;
  OwnerPhone: string | null;
  Possession: string[];
  PostalCity: string | null;
  RoomsTotal: number;
  StreetName: string | null;
  TenantPays: string[];
  Topography: string | null;
  UnitNumber: string | null;
  Vegetation: string[];
  WoodedArea: string | null;
  BuilderName: string;
  CommonWalls: string[];
  Concessions: string | null;
  Contingency: string;
  CrossStreet: string | null;
  Disclosures: string[];
  FireplaceYN: boolean;
  FuelExpense: number | null;
  GrossIncome: number | null;
  LandLeaseYN: boolean;
  LeaseAmount: number | null;
  ListTeamKey: string | null;
  LockBoxType: string[];
  LotFeatures: string[];
  MobileWidth: number | null;
  PastureArea: number | null;
  PetsAllowed: string[];
  PhotosCount: number;
  PoolExpense: number | null;
  PossibleUse: string[];
  ShowingDays: string | null;
  SpaFeatures: string[];
  StateRegion: string | null;
  SyndicateTo: string[];
  VideosCount: number | null;
  WaterSource: string[];
  BuilderModel: string;
  BuildingName: string;
  BusinessName: string;
  BusinessType: string[];
  BuyerTeamKey: string | null;
  CarrierRoute: string | null;
  DaysOnMarket: number;
  DoorFeatures: string[];
  FrontageType: string[];
  GarageSpaces: number;
  LeasableArea: number | null;
  ListAgentAOR: string | null;
  ListAgentFax: string | null;
  ListAgentKey: string;
  ListAgentURL: string | null;
  ListPriceLow: number | null;
  ListTeamName: string | null;
  ListingTerms: string[];
  LotSizeAcres: number;
  LotSizeUnits: string | null;
  MLSAreaMajor: string | null;
  MLSAreaMinor: string | null;
  MobileLength: number | null;
  NumberOfLots: number | null;
  NumberOfPads: number | null;
  OccupantName: string;
  OccupantType: string;
  OnMarketDate: string;
  OtherExpense: number | null;
  OtherParking: string | null;
  ParcelNumber: string;
  ParkingTotal: number;
  PoolFeatures: string[];
  RentIncludes: string[];
  StoriesTotal: number;
  StreetNumber: string | null;
  StreetSuffix: string | null;
  TaxMapNumber: string | null;
  TrashExpense: number | null;
  UnitTypeType: string | null;
  WaterfrontYN: boolean;
  AssociationYN: boolean;
  BathroomsFull: number;
  BuyerAgentAOR: string | null;
  BuyerAgentFax: string | null;
  BuyerAgentKey: string | null;
  BuyerAgentURL: string | null;
  BuyerTeamName: string | null;
  CarportSpaces: number;
  CountryRegion: string | null;
  CoveredSpaces: number;
  EntryLocation: string;
  GreenLocation: string[];
  ListOfficeAOR: string | null;
  ListOfficeFax: string | null;
  ListOfficeKey: string;
  ListOfficeURL: string | null;
  LotSizeSource: string;
  MapCoordinate: string | null;
  OccupantPhone: string;
  OffMarketDate: string | null;
  OpenParkingYN: boolean;
  OwnershipType: string | null;
  PoolPrivateYN: boolean;
  RentControlYN: boolean | null;
  StructureType: string[];
  TaxBookNumber: string | null;
  TaxExemptions: string[];
  WaterBodyName: string | null;
  WithdrawnDate: string | null;
  '@odata.context': string;
  ApprovalStatus: string | null;
  AssociationFee: number;
  BuyerFinancing: string[];
  BuyerOfficeAOR: string | null;
  BuyerOfficeFax: string | null;
  BuyerOfficeKey: string | null;
  BuyerOfficeURL: string | null;
  CableTvExpense: number | null;
  CoListAgentAOR: string | null;
  CoListAgentFax: string | null;
  CoListAgentKey: string | null;
  CoListAgentURL: string | null;
  CommonInterest: string | null;
  ContingentDate: string;
  CountyOrParish: string;
  CultivatedArea: number | null;
  DirectionFaces: string;
  DocumentsCount: number;
  ElevationUnits: string;
  ExpirationDate: string | null;
  FoundationArea: number;
  FrontageLength: string;
  GardnerExpense: number | null;
  HomeWarrantyYN: boolean;
  HorseAmenities: string[];
  IncomeIncludes: string[];
  ListAgentEmail: string | null;
  ListAgentPager: string | null;
  ListingService: string;
  ManagerExpense: number | null;
  MobileDimUnits: string | null;
  OtherEquipment: string[];
  PrivateRemarks: string;
  ShowingEndTime: string | null;
  SourceSystemID: string | null;
  UnitsFurnished: string | null;
  WindowFeatures: string[];
  AssociationFee2: number;
  AssociationName: string;
  BuyerAgentEmail: string | null;
  BuyerAgentMlsId: string | null;
  BuyerAgentPager: string | null;
  BuyerOfficeName: string | null;
  CancelationDate: string | null;
  CoBuyerAgentAOR: string | null;
  CoBuyerAgentFax: string | null;
  CoBuyerAgentKey: string | null;
  CoBuyerAgentURL: string | null;
  CoListOfficeAOR: string | null;
  CoListOfficeFax: string | null;
  CoListOfficeKey: string | null;
  CoListOfficeURL: string | null;
  ContinentRegion: string | null;
  CopyrightNotice: string;
  CropsIncludedYN: boolean | null;
  ElectricExpense: number | null;
  FireplacesTotal: number;
  GardenerExpense: number | null;
  LandLeaseAmount: number;
  LaundryFeatures: string[];
  LeaseExpiration: string | null;
  LicensesExpense: number | null;
  ListOfficeEmail: string | null;
  ListOfficePhone: string | null;
  LivingAreaUnits: string;
  LockBoxLocation: string;
  MajorChangeType: string;
  NewTaxesExpense: number | null;
  OtherStructures: string[];
  ParkManagerName: string | null;
  ParkingFeatures: string[];
  PostalCodePlus4: string | null;
  RoadSurfaceType: string[];
  SeatingCapacity: number | null;
  SourceSystemKey: string | null;
  SpecialLicenses: string[];
  StateOrProvince: string;
  StreetDirPrefix: string | null;
  StreetDirSuffix: string | null;
  SubdivisionName: string;
  SuppliesExpense: number | null;
  TaxAnnualAmount: number;
  TaxParcelLetter: string | null;
  TotalActualRent: number | null;
  YearBuiltSource: string;
  YearEstablished: number | null;
  AnchorsCoTenants: string;
  AssociationName2: string;
  AssociationPhone: string;
  AttachedGarageYN: boolean;
  AvailabilityDate: string;
  BathroomsPartial: number;
  BedroomsPossible: number;
  BuildingFeatures: string[];
  BuyerOfficeEmail: string | null;
  BuyerOfficeMlsId: string | null;
  BuyerOfficePhone: string | null;
  CoBuyerOfficeAOR: string | null;
  CoBuyerOfficeFax: string | null;
  CoBuyerOfficeKey: string | null;
  CoBuyerOfficeURL: string | null;
  CoListAgentEmail: string | null;
  CoListAgentMlsId: string | null;
  CoListAgentPager: string | null;
  CoListOfficeName: string | null;
  CurrentFinancing: string[];
  ElementarySchool: string;
  ExteriorFeatures: string[];
  InsuranceExpense: number | null;
  InteriorFeatures: string[];
  IrrigationSource: string[];
  LaborInformation: string[];
  ListingAgreement: string | null;
  LivingAreaSource: string;
  OperatingExpense: number | null;
  ParkManagerPhone: string | null;
  PendingTimestamp: string;
  RoadFrontageType: string[];
  SecurityFeatures: string[];
  ShowingStartTime: string | null;
  SignOnPropertyYN: boolean;
  SourceSystemName: string | null;
  TaxAssessedValue: number;
  TaxStatusCurrent: string[];
  VacancyAllowance: number | null;
  YearBuiltDetails: string;
  AssociationPhone2: string;
  BuildingAreaUnits: string;
  CoBuyerAgentEmail: string | null;
  CoBuyerAgentMlsId: string | null;
  CoBuyerAgentPager: string | null;
  CoBuyerOfficeName: string | null;
  CoListOfficeEmail: string | null;
  CoListOfficeMlsId: string | null;
  CoListOfficePhone: string | null;
  CommunityFeatures: string[];
  ConcessionsAmount: number | null;
  DevelopmentStatus: string[];
  ExistingLeaseType: string[];
  FarmLandAreaUnits: string | null;
  FireplaceFeatures: string[];
  FoundationDetails: string[];
  LeasableAreaUnits: string | null;
  LeaseAssignableYN: boolean | null;
  LeaseConsideredYN: boolean;
  ListAgentLastName: string;
  ListingKeyNumeric: number | null;
  LotSizeDimensions: string;
  LotSizeSquareFeet: number;
  MainLevelBedrooms: number | null;
  NewConstructionYN: boolean;
  NumberOfBuildings: number | null;
  NumberOfUnitsMoMo: number | null;
  OnMarketTimestamp: string | null;
  OpenParkingSpaces: number | null;
  OriginalListPrice: number;
  PreviousListPrice: number;
  PropertyCondition: string[];
  PublicSurveyRange: string | null;
  SeniorCommunityYN: boolean;
  ShowingAttendedYN: boolean | null;
  WaterSewerExpense: number | null;
  YearsCurrentOwner: number | null;
  ZoningDescription: string;
  ArchitecturalStyle: string[];
  BuildingAreaSource: string;
  BuyerAgentFullName: string | null;
  BuyerAgentLastName: string | null;
  CoBuyerOfficeEmail: string | null;
  CoBuyerOfficeMlsId: string | null;
  CoBuyerOfficePhone: string | null;
  DistanceToBusUnits: string | null;
  DistanceToGasUnits: string | null;
  DocumentsAvailable: string[];
  FarmLandAreaSource: string | null;
  HighSchoolDistrict: string;
  IDXParticipationYN: boolean;
  ListAgentCellPhone: string | null;
  ListAgentFirstName: string;
  ListAgentHomePhone: string | null;
  ListAgentVoiceMail: string | null;
  ListOfficePhoneExt: string | null;
  ListTeamKeyNumeric: number | null;
  MainLevelBathrooms: number;
  MaintenanceExpense: number | null;
  NetOperatingIncome: number | null;
  NumberOfUnitsTotal: number;
  OffMarketTimestamp: string | null;
  PestControlExpense: number | null;
  PropertyAttachedYN: boolean;
  RoadResponsibility: string[];
  ShowingContactName: string;
  ShowingContactType: string[];
  SyndicationRemarks: string | null;
  WaterfrontFeatures: string[];
  YearBuiltEffective: number | null;
  AdditionalParcelsYN: boolean;
  BathroomsOneQuarter: number;
  BuyerAgentCellPhone: string | null;
  BuyerAgentFirstName: string | null;
  BuyerAgentHomePhone: string | null;
  BuyerAgentVoiceMail: string | null;
  BuyerOfficePhoneExt: string | null;
  BuyerTeamKeyNumeric: number | null;
  CoListAgentFullName: string | null;
  CoListAgentLastName: string | null;
  ConcessionsComments: string | null;
  FinancialDataSource: string[];
  GrazingPermitsBlmYN: boolean | null;
  GreenSustainability: string[];
  ListAgentKeyNumeric: number | null;
  ListAgentMiddleName: string;
  ListAgentNamePrefix: string | null;
  ListAgentNameSuffix: string | null;
  ListingContractDate: string;
  LockBoxSerialNumber: string;
  LotDimensionsSource: string;
  MapCoordinateSource: string | null;
  MobileHomeRemainsYN: boolean | null;
  NumberOfUnitsLeased: number | null;
  NumberOfUnitsVacant: number | null;
  OriginatingSystemID: string;
  PowerProductionType: string | null;
  PropertyUniversalID: string | null;
  PublicSurveySection: string | null;
  RVParkingDimensions: string | null;
  ShowingContactPhone: string;
  ShowingInstructions: string;
  ShowingRequirements: string | null;
  StreetNumberNumeric: number | null;
  TaxLegalDescription: string;
  AssociationAmenities: string[];
  BuyerAgentKeyNumeric: number | null;
  BuyerAgentMiddleName: string | null;
  BuyerAgentNamePrefix: string | null;
  BuyerAgentNameSuffix: string | null;
  CoBuyerAgentFullName: string | null;
  CoBuyerAgentLastName: string | null;
  CoListAgentCellPhone: string | null;
  CoListAgentFirstName: string | null;
  CoListAgentHomePhone: string | null;
  CoListAgentVoiceMail: string | null;
  CoListOfficePhoneExt: string | null;
  DistanceToBusNumeric: number | null;
  DistanceToGasNumeric: number | null;
  DistanceToSewerUnits: number | null;
  DistanceToWaterUnits: number | null;
  ElectricOnPropertyYN: boolean | null;
  GreenEnergyEfficient: string[];
  GrossScheduledIncome: number | null;
  HabitableResidenceYN: boolean | null;
  HoursDaysOfOperation: string[];
  LeaseAmountFrequency: string | null;
  LeaseRenewalOptionYN: boolean | null;
  ListAgentDesignation: string[];
  ListAgentDirectPhone: string | null;
  ListAgentMobilePhone: string | null;
  ListAgentOfficePhone: string | null;
  ListOfficeKeyNumeric: number | null;
  MajorChangeTimestamp: string | null;
  MiddleOrJuniorSchool: string;
  OriginatingSystemKey: string;
  PriceChangeTimestamp: string;
  PrivateOfficeRemarks: string;
  PublicSurveyTownship: string | null;
  PurchaseContractDate: string | null;
  ShowingAdvanceNotice: string | null;
  StreetAdditionalInfo: string | null;
  StreetSuffixModifier: string | null;
  VacancyAllowanceRate: number | null;
  VirtualTourURLZillow: string | null;
  AccessibilityFeatures: string[];
  BathroomsThreeQuarter: number;
  BathroomsTotalDecimal: number;
  BuyerAgentDesignation: string[];
  BuyerAgentDirectPhone: string | null;
  BuyerAgentMobilePhone: string | null;
  BuyerAgentOfficePhone: string | null;
  BuyerOfficeKeyNumeric: number | null;
  CoBuyerAgentCellPhone: string | null;
  CoBuyerAgentFirstName: string | null;
  CoBuyerAgentHomePhone: string | null;
  CoBuyerAgentVoiceMail: string | null;
  CoBuyerOfficePhoneExt: string | null;
  CoListAgentKeyNumeric: number | null;
  CoListAgentMiddleName: string | null;
  CoListAgentNamePrefix: string | null;
  CoListAgentNameSuffix: string | null;
  ConstructionMaterials: string[];
  DistanceToBusComments: string | null;
  DistanceToGasComments: string | null;
  DistanceToStreetUnits: string | null;
  GreenEnergyGeneration: string[];
  GreenIndoorAirQuality: string[];
  ListAgentStateLicense: string | null;
  ListAgentVoiceMailExt: string | null;
  PatioAndPorchFeatures: string[];
  PhotosChangeTimestamp: string | null;
  StatusChangeTimestamp: string;
  SubAgencyCompensation: string | null;
  VideosChangeTimestamp: string | null;
  VirtualTourURLBranded: string | null;
  AboveGradeFinishedArea: number;
  AssociationFeeIncludes: string[];
  BelowGradeFinishedArea: number;
  BuyerAgentStateLicense: string | null;
  BuyerAgentVoiceMailExt: string | null;
  CoBuyerAgentKeyNumeric: number | null;
  CoBuyerAgentMiddleName: string | null;
  CoBuyerAgentNamePrefix: string | null;
  CoBuyerAgentNameSuffix: string | null;
  CoListAgentDesignation: string[];
  CoListAgentDirectPhone: string | null;
  CoListAgentMobilePhone: string | null;
  CoListAgentOfficePhone: string | null;
  CoListOfficeKeyNumeric: number | null;
  CumulativeDaysOnMarket: number | null;
  DistanceToFreewayUnits: string | null;
  DistanceToSchoolsUnits: string | null;
  DistanceToSewerNumeric: number | null;
  DistanceToWaterNumeric: number | null;
  GreenWaterConservation: string[];
  ListAgentTollFreePhone: string | null;
  OriginalEntryTimestamp: string;
  ShowingContactPhoneExt: string | null;
  AssociationFeeFrequency: string;
  BuyerAgencyCompensation: string | null;
  BuyerAgentTollFreePhone: string | null;
  CoBuyerAgentDesignation: string[];
  CoBuyerAgentDirectPhone: string | null;
  CoBuyerAgentMobilePhone: string | null;
  CoBuyerAgentOfficePhone: string | null;
  CoBuyerOfficeKeyNumeric: number | null;
  CoListAgentStateLicense: string | null;
  CoListAgentVoiceMailExt: string | null;
  DistanceToElectricUnits: string | null;
  DistanceToSewerComments: string | null;
  DistanceToShoppingUnits: string | null;
  DistanceToStreetNumeric: number | null;
  DistanceToWaterComments: string | null;
  FarmCreditServiceInclYN: boolean | null;
  GrazingPermitsPrivateYN: boolean | null;
  IrrigationWaterRightsYN: boolean | null;
  LandLeaseExpirationDate: string | null;
  ListAgentOfficePhoneExt: string | null;
  ListAgentPreferredPhone: string;
  VirtualTourURLUnbranded: string | null;
  AssociationFee2Frequency: string;
  BuyerAgentOfficePhoneExt: string | null;
  BuyerAgentPreferredPhone: string | null;
  CoBuyerAgentStateLicense: string | null;
  CoBuyerAgentVoiceMailExt: string | null;
  CoListAgentTollFreePhone: string | null;
  ContractStatusChangeDate: string;
  DistanceToFreewayNumeric: number | null;
  DistanceToSchoolBusUnits: string | null;
  DistanceToSchoolsNumeric: number | null;
  DistanceToStreetComments: string | null;
  DocumentsChangeTimestamp: string | null;
  ElementarySchoolDistrict: string;
  LandLeaseAmountFrequency: string;
  LeaseRenewalCompensation: string[];
  NumberOfUnitsInCommunity: number | null;
  OperatingExpenseIncludes: string[];
  SpecialListingConditions: string[];
  CoBuyerAgentTollFreePhone: string | null;
  CoListAgentOfficePhoneExt: string | null;
  CoListAgentPreferredPhone: string | null;
  DistanceToElectricNumeric: number | null;
  DistanceToFreewayComments: string | null;
  DistanceToSchoolsComments: string | null;
  DistanceToShoppingNumeric: number | null;
  InternetConsumerCommentYN: boolean;
  ListingInputOriginalMedia: string | null;
  NumberOfFullTimeEmployees: number | null;
  NumberOfPartTimeEmployees: number | null;
  NumberOfSeparateGasMeters: number | null;
  SubAgencyCompensationType: string | null;
  CoBuyerAgentOfficePhoneExt: string | null;
  CoBuyerAgentPreferredPhone: string | null;
  DistanceToElectricComments: string | null;
  DistanceToSchoolBusNumeric: number | null;
  DistanceToShoppingComments: string | null;
  DualVariableCompensationYN: boolean;
  IrrigationWaterRightsAcres: number | null;
  ListAgentPreferredPhoneExt: string | null;
  AboveGradeFinishedAreaUnits: string;
  BelowGradeFinishedAreaUnits: string;
  BridgeModificationTimestamp: string;
  BuyerAgencyCompensationType: string | null;
  BuyerAgentPreferredPhoneExt: string | null;
  DistanceToPhoneServiceUnits: string | null;
  DistanceToSchoolBusComments: string | null;
  FurnitureReplacementExpense: number | null;
  NumberOfSeparateWaterMeters: number | null;
  WorkmansCompensationExpense: number | null;
  AboveGradeFinishedAreaSource: string;
  AdditionalParcelsDescription: string | null;
  BelowGradeFinishedAreaSource: string;
  CoListAgentPreferredPhoneExt: string | null;
  MiddleOrJuniorSchoolDistrict: string;
  CoBuyerAgentPreferredPhoneExt: string | null;
  DistanceToPhoneServiceNumeric: number | null;
  DistanceToPlaceofWorshipUnits: string | null;
  GrazingPermitsForestServiceYN: boolean | null;
  GreenBuildingVerificationType: string | null;
  ProfessionalManagementExpense: number | null;
  TransactionBrokerCompensation: number | null;
  DistanceToPhoneServiceComments: string | null;
  InternetEntireListingDisplayYN: boolean;
  NumberOfSeparateElectricMeters: number | null;
  TaxOtherAnnualAssessmentAmount: number | null;
  DistanceToPlaceofWorshipNumeric: number | null;
  HoursDaysOfOperationDescription: string | null;
  DistanceToPlaceofWorshipComments: string | null;
  TransactionBrokerCompensationType: string | null;
  InternetAutomatedValuationDisplayYN: boolean;
}

export type Nullable<T> = { [P in keyof T]: T[P] | undefined };
export type NullablePropertyListing = Nullable<MlsPropertyListing>;

export interface ODataResponse {
  status: string;
  message: string;
  data: {
    '@odata.nextLink': string;
    error: string;
    page_count: number;
    page_size: number;
    success: boolean;
    value: MlsPropertyListing[];
  };
}

export interface ODataStrippedResponse {
  '@odata.nextLink': string;
  error: string;
  page_count: number;
  page_size: number;
  success: boolean;
  value: MlsPropertyListing[];
}
