name: Manual Trigger Workflow for Terraform apply

on:
  workflow_dispatch:
    inputs:
      run_apply:
        description: "Select which environment to apply"
        required: true
        type: choice
        options:
          - PROD-APPLY
          - DEMO-APPLY

env:
  AWS_REGION: us-west-1

jobs:
  apply-terraform-prod:
    name: Deploy PROD ENV Terraform Resources
    if: ${{ inputs.run_apply == 'PROD-APPLY' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.13.5'

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run:  terraform init -backend-config="key=snaphomz-frontend-terraform/prod/terraform.tfstate"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file="prod.tfvars"


  apply-terraform-demo:
    name: Deploy DEMO ENV Terraform Resources
    if: ${{ inputs.run_apply == 'DEMO-APPLY' && github.ref_name == 'release' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.13.5'

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -backend-config="key=snaphomz-frontend-terraform/demo/terraform.tfstate"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file="demo.tfvars"
